---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: default
spec:
  interval: 1m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.8.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 1m
