---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app
  namespace: flux
spec:
  ignore: |-
    dev
    staiging
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/Galphaa/fluxcd.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app
  namespace: flux
spec:
  force: false
  interval: 10m0s
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: app
  validation: client
