apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app
  namespace: flux
spec:
  force: false
  interval: 10m0s
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: app
