---
apiVersion: v1
kind: Namespace
metadata:
  name: gk
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gk-busybox
  name: gk-busybox
  namespace: gk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gk-busybox
  template:
    metadata:
      labels:
        app: gk-busybox
    spec:
      containers:
      - command:
        - sleep
        - 5d
        image: busybox:1.23
        name: busybox
